quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%prod.quarkus.hibernate-orm.schema-management.strategy=none

#Some interesting settings (totally optional):
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.max-size=2
quarkus.datasource.jdbc.initial-size=0
%quarkus.datasource.dev-ui.allow-sql=true
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
quarkus.native.compression.enabled=false
quarkus.native.march=native
quarkus.native.enable-isolates=false
